clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - git push --mirror git@github.com:MarkDownThere/GRAWL.git
          - git push --mirror git@github.com:raffuzzo/GRAWL.git